### ISSUE TITLE
hastebin API has changed.

### ISSUE THREAD

**Issue by Delta-in-hub** [HamzaAnis/vscode-to-hastebin#6]
```
An error occurred when uploading to https://hastebin.com/: Request failed with status code 404
```
`https://hastebin.com/` moves to `https://www.toptal.com/developers/hastebin/`
and  API endpoint has changed.

Could you fix that ? Thanks.

**Comment by HamzaAnis** [comment]
Thank you very much for informing about it. Will send a patch for it soon.

**Comment by HamzaAnis** [comment]
You can set the default hasten server in the configuration. Although I have created the PR which changes the default host but I planned not to merge it because the hastebin.com domain will be there but just redirect to the total domain.

You can find more details over https://github.com/toptal/haste-server/issues/396

People like short links at least short than the toptal one so I am keeping it like that and the extension will create the hastebin.com link but in the future if the extension will break then I'll merge the above PR.

Thanks again for reporting it @Delta-in-hub
